# Generated by Django 3.2.25 on 2025-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=20)),
                ('sub_category', models.CharField(choices=[('tshirts', 'T-Shirts'), ('shirts', 'Shirts'), ('bottom', 'Bottom Wear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('tops_w', 'Tops'), ('bottom_w', 'Bottom Wear'), ('shirts_w', 'Shirts'), ('shoes_w', 'Shoes'), ('accessories_w', 'Accessories')], default='tshirts', max_length=20)),
                ('image', models.URLField(max_length=300)),
            ],
        ),
    ]
